[package]
name = "storm"
version = "0.5.0"
authors = ["Joe Cumbo <mooman219@gmail.com>"]
description = "2D game engine designed for performance"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/storm"
homepage = "https://github.com/mooman219/storm"
repository = "https://github.com/mooman219/storm"
keywords = ["game", "engine", "2D", "graphics"]
categories = ["game-engines"]
edition = "2018"
exclude = ["examples_old/**", "examples/**"]

# This forces docs.rs to build us on windows, which has the simplest build for docs.rs to perform.
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[badges]
maintenance = { status = "experimental" }

[dependencies]
gl = "0.13"
beryllium = "0.1.3"
cgmath = "0.17"
log = "0.4.7"
png = "0.14"
hashbrown = "0.5"
rusttype = "0.7.7"
unicode-normalization = "0.1.8"

[dev-dependencies]
rand = "0.7"
rodio = "0.9"
simple_logger = "1.3"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
